insert into tb_brand (id, name) values (null, "Scania")
insert into tb_brand (id, name) values (null, "Mercedes")
insert into tb_brand (id, name) values (null, "Volvo")
insert into tb_brand (id, name) values (null, "Volkswagen")
insert into tb_vehicle_model (id, name, brand_id) values (null, "R114", 1)
insert into tb_vehicle_model (id, name, brand_id) values (null, "P310", 1)
insert into tb_vehicle_model (id, name, brand_id) values (null, "LS 1634", 2)
insert into tb_vehicle_model (id, name, brand_id) values (null, "25390", 4)
insert into tb_vehicle_model (id, name, brand_id) values (null, "FH12", 3)
insert into tb_vehicle (id, license_plate, model_year, model_vehicle_id) values (null, "AAA1A111", 2020, 1)
insert into tb_vehicle (id, license_plate, model_year, model_vehicle_id) values (null, "BBB1A111", 2019, 1)
insert into tb_vehicle (id, license_plate, model_year, model_vehicle_id) values (null, "CCC1A111", 2018, 3)
insert into tb_vehicle (id, license_plate, model_year, model_vehicle_id) values (null, "DDD1A111", 2000, 2)
insert into tb_vehicle (id, license_plate, model_year, model_vehicle_id) values (null, "EEE1A111", 1999, 5)
insert into tb_vehicle (id, license_plate, model_year, model_vehicle_id) values (null, "FFF1A111", 1998, 3)
insert into tb_vehicle (id, license_plate, model_year, model_vehicle_id) values (null, "GGG1A111", 2020, 3)
insert into tb_supply (id, moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id, average_consumption) values (null, "2020-01-01T00:00:00Z", 500, "60.", true, 3, 1, null)
insert into tb_supply (id, moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id, average_consumption) values (null, "2020-01-01T00:00:00Z", 1000, "90.0", false, 3, 1, null)
insert into tb_supply (id, moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id, average_consumption) values (null, "2020-01-01T00:00:00Z", 1300, "95.0", true, 3, 1, null)
insert into tb_supply (id, moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id, average_consumption) values (null, "2020-01-01T00:00:00Z", 2000, "110.0", true, 3, 1, null)
insert into tb_supply (id, moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id, average_consumption) values (null, "2020-01-01T00:00:00Z", 1000, "80.0", true, 3, 2, null)
insert into tb_supply (id, moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id, average_consumption) values (null, "2020-01-01T00:00:00Z", 1500, "130.0", false, 3, 2, null)