drop table tb_supply;
drop table tb_vehicle;
drop table tb_vehicle_model;
drop table tb_brand;

create table tb_brand (id int8 generated by default as identity, image_url varchar(255), name varchar(255), primary key (id));
create table tb_supply (id int8 generated by default as identity, fuel int4, full_tank boolean not null, liters_filled float8, moment timestamp, odometer int4, price_total float8, total_journey_from_full_tank int4, total_liters_with_the_journey float8, vehicle_id int8, primary key (id));
create table tb_vehicle (id int8 generated by default as identity, license_plate varchar(255), model_year int4, tank_capacity int4, model_vehicle_id int8, primary key (id));
create table tb_vehicle_model (id int8 generated by default as identity, name varchar(255), brand_id int8, primary key (id));
alter table if exists tb_supply add constraint FKoriev9q11t15jpv8kbjp1lbuc foreign key (vehicle_id) references tb_vehicle;
alter table if exists tb_vehicle add constraint FK84mcgp0tfiobn66le0743b1od foreign key (model_vehicle_id) references tb_vehicle_model;
alter table if exists tb_vehicle_model add constraint FKarf0uc8w9oo917ckpofdlqtcu foreign key (brand_id) references tb_brand;