INSERT INTO public.tb_brand (name) VALUES ('Scania');
INSERT INTO public.tb_brand (name) VALUES ('Mercedes');
INSERT INTO public.tb_brand (name) VALUES ('Volvo');
INSERT INTO public.tb_brand (name) VALUES ('Volkswagen');
INSERT INTO public.tb_vehicle_model (name, brand_id) VALUES ('R114', 1);
INSERT INTO public.tb_vehicle_model (name, brand_id) VALUES ('P310', 1);
INSERT INTO public.tb_vehicle_model (name, brand_id) VALUES ('LS 1634', 2);
INSERT INTO public.tb_vehicle_model (name, brand_id) VALUES ('25390', 4);
INSERT INTO public.tb_vehicle_model (name, brand_id) VALUES ('FH12', 3);
INSERT INTO public.tb_vehicle (license_plate, model_year, model_vehicle_id) VALUES ('AAA1A111', 2020, 1);
INSERT INTO public.tb_vehicle (license_plate, model_year, model_vehicle_id) VALUES ('BBB1A111', 2019, 1);
INSERT INTO public.tb_vehicle (license_plate, model_year, model_vehicle_id) VALUES ('CCC1A111', 2018, 3);
INSERT INTO public.tb_vehicle (license_plate, model_year, model_vehicle_id) VALUES ('DDD1A111', 2000, 2);
INSERT INTO public.tb_vehicle (license_plate, model_year, model_vehicle_id) VALUES ('EEE1A111', 1999, 5);
INSERT INTO public.tb_vehicle (license_plate, model_year, model_vehicle_id) VALUES ('FFF1A111', 1998, 3);
INSERT INTO public.tb_vehicle (license_plate, model_year, model_vehicle_id) VALUES ('GGG1A111', 2020, 3);
INSERT INTO public.tb_supply (moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id) VALUES ('2020-01-01T00:00:00Z', 500, '60.', true, 3, 1);
INSERT INTO public.tb_supply (moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id) VALUES ('2020-01-01T00:00:00Z', 1000, '90.0', false, 3, 1); 
INSERT INTO public.tb_supply (moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id) VALUES ('2020-01-01T00:00:00Z', 1300, '95.0', true, 3, 1);
INSERT INTO public.tb_supply (moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id) VALUES ('2020-01-01T00:00:00Z', 2000, '110.0', true, 3, 1); 
INSERT INTO public.tb_supply (moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id) VALUES ('2020-01-01T00:00:00Z', 1000, '80.0', true, 3, 2);
INSERT INTO public.tb_supply (moment, odometer, liter_value_of_fuel, full_tank, fuel, vehicle_id) VALUES ('2020-01-01T00:00:00Z', 1500, '130.0', false, 3, 2);